defs:
  - typesRef: &types-ref
      - label: "Sections"
        name: "sections"
        widget: "list"
        collapsed: true
        types:
          - label: "Hero"
            name: "hero"
            widget: object
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Description",
                  name: "description",
                  widget: "text",
                  required: false,
                }
              - {
                  label: "Hero Image",
                  name: "hero_image",
                  widget: "image",
                  media_library: { config: { multiple: false } },
                }
              - {
                  label: "Button Text",
                  name: "cta_text",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Button Link",
                  name: "cta_link",
                  widget: "string",
                  required: false,
                }

          - label: "Rolling Hills"
            name: "rolling_hills"
            widget: object
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Sub Heading", name: "sub_heading", widget: "text" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Tag Line", name: "tag_line", widget: "text" }
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  media_library: { config: { multiple: false } },
                }

          - label: "HorizontalScroll"
            name: "horizontal_scroll"
            widget: object
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Sub Heading", name: "sub_heading", widget: "text" }
              - {
                  label: "Items",
                  name: "items",
                  widget: "list",
                  field:
                    {
                      label: "Item",
                      name: "item",
                      widget: "object",
                      fields:
                        [
                          { label: "Title", name: "title", widget: "string" },
                          {
                            label: "Description",
                            name: "description",
                            widget: "text",
                          },
                          {
                            label: "Image",
                            name: "image",
                            widget: "image",
                            media_library: { config: { multiple: false } },
                          },
                        ],
                    },
                }

local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Basic"
        name: "basic"
        file: "content/pages/basic.md"
        fields:
          - label: "Full Logo"
            name: "full_logo"
            widget: "image"
            media_library: { config: { multiple: false } }

          - label: "Mini Logo"
            name: "mini_logo"
            widget: "image"
            media_library: { config: { multiple: false } }

          - label: "Name"
            name: "name"
            widget: "string"

          - label: "Message (Shows in footer)"
            name: "message"
            widget: "text"

          - label: "Phone Number"
            name: "phone_number"
            widget: "string"

          - label: "Email Id"
            name: "email_id"
            widget: "string"

          - label: "Registered Office"
            name: "registered_office"
            widget: "text"

          - label: "Corporate Office"
            name: "corporate_office"
            widget: "text"

          - label: "Address (used in footer)"
            name: "address"
            widget: "text"

          - label: "Linkedin"
            name: "linkedin"
            widget: "string"
            required: false

          - label: "Instagram"
            name: "instagram"
            widget: "string"
            required: false

          - label: "Facebook"
            name: "facebook"
            widget: "string"
            required: false

          - label: "X"
            name: "x"
            widget: "string"
            required: false

      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields: *types-ref

      - label: "General Design Elements"
        name: "general_design"
        file: "content/pages/general-design.md"
        fields:
          - {
              label: "Rolling Hills Background",
              name: "rolling_hills_bg",
              widget: "image",
              media_library: { config: { multiple: false } },
            }
          - {
              label: "Rolling Hills Foreground",
              name: "rolling_hills_fg",
              widget: "image",
              media_library: { config: { multiple: false } },
            }
          - {
              label: "Tag Flair",
              name: "tag_flair",
              widget: "image",
              media_library: { config: { multiple: false } },
            }
